# ========================================
# Target Reconstruction - Configuration
# ========================================

# ========== Image Configuration ==========
image:
  width: 1280
  height: 1024
  grid_size: 1           # Grid size for feature competition (pixels), 控制最终点云密度
  border_pixels: 20       # Ignore border region (pixels)
  
  # 采样步长（控制遍历速度）
  sampling_step_inside_mask: 1   # Step for pixels INSIDE mask (dense sampling)
  sampling_step_outside_mask: 5  # Step for pixels OUTSIDE mask (sparse sampling)

# ========== Depth Configuration ==========
depth:
  min_depth: 0.1          # Minimum valid depth (meters)
  max_depth: 5.0          # Maximum valid depth (meters)
  noise_threshold: 0.05   # Depth noise threshold (meters)

# ========== Feature Extraction ==========
feature:
  min_shi_tomasi_score: 5.0    # Minimum corner response
  max_points_per_grid: 1       # Maximum features per grid cell

# ========== Quality Control ==========
quality:
  min_observations: 3           # Minimum observations to keep a point
  max_reprojection_error: 2.0   # Maximum reprojection error (pixels)
  min_confidence: 0.3           # Minimum confidence score [0, 1]

# ========== Map Management ==========
map:
  voxel_size: 0.05       # Voxel size for map (meters), 5cm for fine reconstruction
  enable_color: true     # Enable RGB color for points
  enable_tsdf: false     # Enable TSDF fusion (experimental)

# ========== ROS Topics ==========
# Topic names for subscribing to sensor data
topics:
  # RGB camera topic
  rgb_image: "/realsense/depth_camera/color/image_raw"
  
  # Depth camera topic
  depth_image: "/realsense/depth_camera/depth/image_raw"
  
  # YOLO person segmentation mask (255=person, 0=background)
  person_mask: "/yolo/person_mask"
  
  # Odometry topic (IMU/Body frame pose from ground truth system)
  # e.g., from Gazebo, Vicon, FAST-LIVO2, etc.
  odometry: "/mavros/local_position/odom"
  
  # Point cloud output topics (published by this node)
  # Reconstructed point clouds (融合重建后的点云)
  reconstructed_cloud_global: "/target_reconstruction/reconstructed_cloud_global"  # 累积地图 - 全局系 (frame: map)
  reconstructed_cloud_body: "/target_reconstruction/reconstructed_cloud_body"      # 当前帧重建点 - 机体系 (frame: body)
  
  # Raw depth point clouds (当前帧原始深度点云，全部像素降采样)
  depth_cloud_body: "/target_reconstruction/depth_cloud_body"     # 机体系 (frame: body)
  depth_cloud_global: "/target_reconstruction/depth_cloud_global" # 全局系 (frame: map)

# ========== Camera Intrinsics ==========
# Example values for RealSense D435
# Please calibrate and update these values for your camera
camera:
  fx: 639.9976491530514
  fy: 639.9976491530514
  cx: 640.5
  cy: 512.5

# ========== Extrinsics: IMU/Body to Camera ==========
# Transformation from IMU (drone body) frame to camera frame
# Update these values based on your sensor setup
extrinsics:
  # Rotation matrix R_i_c (row-major, 3x3)
  # R_i_c[0]: first row
  # R_i_c[1]: second row  
  # R_i_c[2]: third row
  R_i_c:
    - [0.0, 0.0, 1.0]
    - [-1.0, 0.0, 0.0]
    - [0.0, -1.0, 0.0]
  
  # Translation vector t_i_c (meters, 3x1)
  t_i_c: [0.1, 0.0, 0.0]

# ========== Processing Thread ==========
threading:
  max_queue_size: 10      # Maximum frame buffer size
  # Larger values: more robust to computation spikes, more memory
  # Smaller values: less memory, may drop frames if processing is slow

# ========== Publishing ==========
publishing:
  rate: 5.0               # Point cloud publish rate (Hz)

# ========== Output ==========
output:
  file: "target_reconstruction.ply"   # Output file name (relative to package output folder)

